<?php

namespace Skills\ClaimChecks;

use Illuminate\Routing\PendingResourceRegistration;
use Illuminate\Routing\Route as RouteObject;
use Illuminate\Support\Facades\Route;
use PHPUnit\Framework\Attributes\Test;
use Skills\ClaimChecks\Stubs\PlainInvokableController;
use Skills\ClaimChecks\Stubs\StubController;

/**
 * Claims made by: request-handling/skills/request-handling/SKILL.md
 */
class RequestHandlingClaimsTest extends TestCase
{
    #[Test]
    public function closure_routes_can_still_be_serialized_for_the_route_cache(): void
    {
        // "Closure routes do not break route:cache. prepareForSerialization() wraps
        // them with SerializableClosure... The rule is repeated everywhere and has
        // been wrong for years."
        $route = new RouteObject('GET', '/cached', fn () => 'ok');

        $route->prepareForSerialization();

        $this->assertIsString($route->getAction('uses'), 'A closure route no longer serializes; the version note needs rewriting');
    }

    #[Test]
    public function middleware_can_be_applied_to_named_resource_methods(): void
    {
        // "middlewareFor() and withoutMiddlewareFor() apply middleware to named methods
        // of a resource or singleton route, so 'these two actions need different
        // middleware' is no longer a reason to abandon the resource."
        foreach (['middleware', 'middlewareFor', 'withoutMiddlewareFor'] as $method) {
            $this->assertTrue(
                method_exists(PendingResourceRegistration::class, $method),
                "PendingResourceRegistration::{$method}() is gone; signal 4 in the skill depends on it",
            );
        }
    }

    #[Test]
    public function api_resource_registers_exactly_the_five_non_form_actions(): void
    {
        // "Route::apiResource registers exactly index, show, store, update, destroy.
        // Writing Route::resource(...)->only([those five]) is the same thing, longhand."
        Route::apiResource('widgets', StubController::class);

        $actions = collect(Route::getRoutes()->getRoutes())
            ->map(fn (RouteObject $route) => $route->getActionMethod())
            ->values()
            ->sort()
            ->values()
            ->all();

        $this->assertSame(['destroy', 'index', 'show', 'store', 'update'], $actions);
    }

    #[Test]
    public function a_controller_does_not_need_to_extend_a_base_class(): void
    {
        // "The base Controller generated by current Laravel is an empty abstract class;
        // it does not bring AuthorizesRequests or ValidatesRequests with it."
        Route::get('/plain', PlainInvokableController::class);

        $this->get('/plain')->assertOk()->assertSee('ok');
    }
}
